# Linker order for every file, passed to the Metrowerks linker.

O_FILES :=                                       \
    $(BUILD_DIR)/asm/mq-j/xlCoreGCN.o            \
    $(BUILD_DIR)/asm/mq-j/xlPostGCN.o            \
    $(BUILD_DIR)/asm/mq-j/xlFileGCN.o            \
    $(BUILD_DIR)/asm/mq-j/xlList.o               \
    $(BUILD_DIR)/asm/mq-j/xlHeap.o               \
    $(BUILD_DIR)/asm/mq-j/xlObject.o             \
    $(BUILD_DIR)/asm/mq-j/simGCN.o               \
    $(BUILD_DIR)/asm/mq-j/movie.o                \
    $(BUILD_DIR)/asm/mq-j/THPPlayer.o            \
    $(BUILD_DIR)/asm/mq-j/THPAudioDecode.o       \
    $(BUILD_DIR)/asm/mq-j/THPDraw.o              \
    $(BUILD_DIR)/asm/mq-j/THPRead.o              \
    $(BUILD_DIR)/asm/mq-j/THPVideoDecode.o       \
    $(BUILD_DIR)/asm/mq-j/mcardGCN.o             \
    $(BUILD_DIR)/asm/mq-j/codeGCN.o              \
    $(BUILD_DIR)/asm/mq-j/soundGCN.o             \
    $(BUILD_DIR)/asm/mq-j/frame.o                \
    $(BUILD_DIR)/asm/mq-j/system.o               \
    $(BUILD_DIR)/asm/mq-j/cpu.o                  \
    $(BUILD_DIR)/asm/mq-j/pif.o                  \
    $(BUILD_DIR)/asm/mq-j/ram.o                  \
    $(BUILD_DIR)/asm/mq-j/rom.o                  \
    $(BUILD_DIR)/asm/mq-j/rdp.o                  \
    $(BUILD_DIR)/asm/mq-j/rdb.o                  \
    $(BUILD_DIR)/asm/mq-j/rsp.o                  \
    $(BUILD_DIR)/asm/mq-j/mips.o                 \
    $(BUILD_DIR)/asm/mq-j/disk.o                 \
    $(BUILD_DIR)/asm/mq-j/flash.o                \
    $(BUILD_DIR)/asm/mq-j/sram.o                 \
    $(BUILD_DIR)/asm/mq-j/audio.o                \
    $(BUILD_DIR)/asm/mq-j/video.o                \
    $(BUILD_DIR)/asm/mq-j/serial.o               \
    $(BUILD_DIR)/asm/mq-j/library.o              \
    $(BUILD_DIR)/asm/mq-j/peripheral.o           \
    $(BUILD_DIR)/asm/mq-j/_frameGCNcc.o          \
    $(BUILD_DIR)/asm/mq-j/_buildtev.o            \
    $(BUILD_DIR)/asm/mq-j/PPCArch.o              \
    $(BUILD_DIR)/asm/mq-j/OS.o                   \
    $(BUILD_DIR)/asm/mq-j/OSAlarm.o              \
    $(BUILD_DIR)/asm/mq-j/OSAlloc.o              \
    $(BUILD_DIR)/asm/mq-j/OSArena.o              \
    $(BUILD_DIR)/asm/mq-j/OSAudioSystem.o        \
    $(BUILD_DIR)/asm/mq-j/OSCache.o              \
    $(BUILD_DIR)/asm/mq-j/OSContext.o            \
    $(BUILD_DIR)/asm/mq-j/OSError.o              \
    $(BUILD_DIR)/asm/mq-j/OSFont.o               \
    $(BUILD_DIR)/asm/mq-j/OSInterrupt.o          \
    $(BUILD_DIR)/asm/mq-j/OSLink.o               \
    $(BUILD_DIR)/asm/mq-j/OSMessage.o            \
    $(BUILD_DIR)/asm/mq-j/OSMemory.o             \
    $(BUILD_DIR)/asm/mq-j/OSMutex.o              \
    $(BUILD_DIR)/asm/mq-j/OSReboot.o             \
    $(BUILD_DIR)/asm/mq-j/OSReset.o              \
    $(BUILD_DIR)/asm/mq-j/OSResetSW.o            \
    $(BUILD_DIR)/asm/mq-j/OSRtc.o                \
    $(BUILD_DIR)/asm/mq-j/OSSync.o               \
    $(BUILD_DIR)/asm/mq-j/OSThread.o             \
    $(BUILD_DIR)/asm/mq-j/OSTime.o               \
    $(BUILD_DIR)/asm/mq-j/__start.o              \
    $(BUILD_DIR)/asm/mq-j/__ppc_eabi_init.o      \
    $(BUILD_DIR)/asm/mq-j/EXIBios.o              \
    $(BUILD_DIR)/asm/mq-j/EXIUart.o              \
    $(BUILD_DIR)/asm/mq-j/SIBios.o               \
    $(BUILD_DIR)/asm/mq-j/SISamplingRate.o       \
    $(BUILD_DIR)/asm/mq-j/vi.o                   \
    $(BUILD_DIR)/asm/mq-j/db.o                   \
    $(BUILD_DIR)/asm/mq-j/mtx.o                  \
    $(BUILD_DIR)/asm/mq-j/mtxvec.o               \
    $(BUILD_DIR)/asm/mq-j/mtx44.o                \
    $(BUILD_DIR)/asm/mq-j/GXInit.o               \
    $(BUILD_DIR)/asm/mq-j/GXFifo.o               \
    $(BUILD_DIR)/asm/mq-j/GXAttr.o               \
    $(BUILD_DIR)/asm/mq-j/GXMisc.o               \
    $(BUILD_DIR)/asm/mq-j/GXGeometry.o           \
    $(BUILD_DIR)/asm/mq-j/GXFrameBuf.o           \
    $(BUILD_DIR)/asm/mq-j/GXLight.o              \
    $(BUILD_DIR)/asm/mq-j/GXTexture.o            \
    $(BUILD_DIR)/asm/mq-j/GXBump.o               \
    $(BUILD_DIR)/asm/mq-j/GXTev.o                \
    $(BUILD_DIR)/asm/mq-j/GXPixel.o              \
    $(BUILD_DIR)/asm/mq-j/GXTransform.o          \
    $(BUILD_DIR)/asm/mq-j/GXPerf.o               \
    $(BUILD_DIR)/asm/mq-j/Padclamp.o             \
    $(BUILD_DIR)/asm/mq-j/Pad.o                  \
    $(BUILD_DIR)/asm/mq-j/dvdlow.o               \
    $(BUILD_DIR)/asm/mq-j/dvdfs.o                \
    $(BUILD_DIR)/asm/mq-j/dvd.o                  \
    $(BUILD_DIR)/asm/mq-j/dvdqueue.o             \
    $(BUILD_DIR)/asm/mq-j/dvderror.o             \
    $(BUILD_DIR)/asm/mq-j/dvdidutils.o           \
    $(BUILD_DIR)/asm/mq-j/dvdFatal.o             \
    $(BUILD_DIR)/asm/mq-j/fstload.o              \
    $(BUILD_DIR)/asm/mq-j/DEMOInit.o             \
    $(BUILD_DIR)/asm/mq-j/DEMOPuts.o             \
    $(BUILD_DIR)/asm/mq-j/DEMOFont.o             \
    $(BUILD_DIR)/asm/mq-j/DEMOPad.o              \
    $(BUILD_DIR)/asm/mq-j/DEMOStats.o            \
    $(BUILD_DIR)/asm/mq-j/ai.o                   \
    $(BUILD_DIR)/asm/mq-j/ar.o                   \
    $(BUILD_DIR)/asm/mq-j/dsp.o                  \
    $(BUILD_DIR)/asm/mq-j/dsp_debug.o            \
    $(BUILD_DIR)/asm/mq-j/dsp_task.o             \
    $(BUILD_DIR)/asm/mq-j/CARDBios.o             \
    $(BUILD_DIR)/asm/mq-j/CARDUnlock.o           \
    $(BUILD_DIR)/asm/mq-j/CARDRdwr.o             \
    $(BUILD_DIR)/asm/mq-j/CARDBlock.o            \
    $(BUILD_DIR)/asm/mq-j/CARDDir.o              \
    $(BUILD_DIR)/asm/mq-j/CARDCheck.o            \
    $(BUILD_DIR)/asm/mq-j/CARDMount.o            \
    $(BUILD_DIR)/asm/mq-j/CARDFormat.o           \
    $(BUILD_DIR)/asm/mq-j/CARDOpen.o             \
    $(BUILD_DIR)/asm/mq-j/CARDCreate.o           \
    $(BUILD_DIR)/asm/mq-j/CARDRead.o             \
    $(BUILD_DIR)/asm/mq-j/CARDWrite.o            \
    $(BUILD_DIR)/asm/mq-j/CARDDelete.o           \
    $(BUILD_DIR)/asm/mq-j/CARDStat.o             \
    $(BUILD_DIR)/asm/mq-j/CARDNet.o              \
    $(BUILD_DIR)/asm/mq-j/THPDec.o               \
    $(BUILD_DIR)/asm/mq-j/THPAudio.o             \
    $(BUILD_DIR)/asm/mq-j/texPalette.o           \
    $(BUILD_DIR)/asm/mq-j/mainloop.o             \
    $(BUILD_DIR)/asm/mq-j/nubevent.o             \
    $(BUILD_DIR)/asm/mq-j/nubinit.o              \
    $(BUILD_DIR)/asm/mq-j/msg.o                  \
    $(BUILD_DIR)/asm/mq-j/msgbuf.o               \
    $(BUILD_DIR)/asm/mq-j/serpoll.o              \
    $(BUILD_DIR)/asm/mq-j/usr_put.o              \
    $(BUILD_DIR)/asm/mq-j/dispatch.o             \
    $(BUILD_DIR)/asm/mq-j/msghndlr.o             \
    $(BUILD_DIR)/asm/mq-j/support.o              \
    $(BUILD_DIR)/asm/mq-j/mutex_TRK.o            \
    $(BUILD_DIR)/asm/mq-j/notify.o               \
    $(BUILD_DIR)/asm/mq-j/flush_cache.o          \
    $(BUILD_DIR)/asm/mq-j/mem_TRK.o              \
    $(BUILD_DIR)/asm/mq-j/__exception.o          \
    $(BUILD_DIR)/asm/mq-j/targimpl.o             \
    $(BUILD_DIR)/asm/mq-j/dolphin_trk.o          \
    $(BUILD_DIR)/asm/mq-j/mpc_7xx_603e.o         \
    $(BUILD_DIR)/asm/mq-j/main_TRK.o             \
    $(BUILD_DIR)/asm/mq-j/dolphin_trk_glue.o     \
    $(BUILD_DIR)/asm/mq-j/targcont.o             \
    $(BUILD_DIR)/asm/mq-j/__mem.o                \
    $(BUILD_DIR)/asm/mq-j/__va_arg.o             \
    $(BUILD_DIR)/asm/mq-j/global_destructor_chain.o \
    $(BUILD_DIR)/asm/mq-j/runtime.o              \
    $(BUILD_DIR)/asm/mq-j/abort_exit.o           \
    $(BUILD_DIR)/asm/mq-j/ansi_files.o           \
    $(BUILD_DIR)/asm/mq-j/ansi_fp.o              \
    $(BUILD_DIR)/asm/mq-j/buffer_io.o            \
    $(BUILD_DIR)/asm/mq-j/critical_regions.ppc_eabi.o \
    $(BUILD_DIR)/asm/mq-j/ctype.o                \
    $(BUILD_DIR)/asm/mq-j/direct_io.o            \
    $(BUILD_DIR)/asm/mq-j/errno.o                \
    $(BUILD_DIR)/asm/mq-j/mbstring.o             \
    $(BUILD_DIR)/asm/mq-j/mem.o                  \
    $(BUILD_DIR)/asm/mq-j/mem_funcs.o            \
    $(BUILD_DIR)/asm/mq-j/misc_io.o              \
    $(BUILD_DIR)/asm/mq-j/printf.o               \
    $(BUILD_DIR)/asm/mq-j/scanf.o                \
    $(BUILD_DIR)/asm/mq-j/string.o               \
    $(BUILD_DIR)/asm/mq-j/strtoul.o              \
    $(BUILD_DIR)/asm/mq-j/uart_console_io.o      \
    $(BUILD_DIR)/asm/mq-j/float.o                \
    $(BUILD_DIR)/asm/mq-j/wchar_io.o             \
    $(BUILD_DIR)/asm/mq-j/e_asin.o               \
    $(BUILD_DIR)/asm/mq-j/e_pow.o                \
    $(BUILD_DIR)/asm/mq-j/fminmaxdim.o           \
    $(BUILD_DIR)/asm/mq-j/s_ceil.o               \
    $(BUILD_DIR)/asm/mq-j/s_copysign.o           \
    $(BUILD_DIR)/asm/mq-j/s_floor.o              \
    $(BUILD_DIR)/asm/mq-j/s_frexp.o              \
    $(BUILD_DIR)/asm/mq-j/s_ldexp.o              \
    $(BUILD_DIR)/asm/mq-j/w_pow.o                \
    $(BUILD_DIR)/asm/mq-j/hyperbolicsf.o         \
    $(BUILD_DIR)/asm/mq-j/log10f.o               \
    $(BUILD_DIR)/asm/mq-j/trigf.o                \
    $(BUILD_DIR)/asm/mq-j/math_inlines.o         \
    $(BUILD_DIR)/asm/mq-j/common_float_tables.o  \
    $(BUILD_DIR)/asm/mq-j/AmcExi2Stubs.o         \
    $(BUILD_DIR)/asm/mq-j/DebuggerDriver.o       \
    $(BUILD_DIR)/asm/mq-j/odenotstub.o           \
