# Linker order for every file, passed to the Metrowerks linker.

O_FILES :=                                  \
    $(BUILD_DIR)/src/xlCoreGCN.o            \
    $(BUILD_DIR)/src/xlPostGCN.o            \
    $(BUILD_DIR)/src/xlFileGCN.o            \
    $(BUILD_DIR)/src/xlList.o               \
    $(BUILD_DIR)/src/xlHeap.o               \
    $(BUILD_DIR)/src/xlObject.o             \
    $(BUILD_DIR)/src/simGCN.o               \
    $(BUILD_DIR)/src/movie.o                \
    $(BUILD_DIR)/src/THPPlayer.o            \
    $(BUILD_DIR)/src/THPAudioDecode.o       \
    $(BUILD_DIR)/src/THPDraw.o              \
    $(BUILD_DIR)/src/THPRead.o              \
    $(BUILD_DIR)/src/THPVideoDecode.o       \
    $(BUILD_DIR)/src/mcardGCN.o             \
    $(BUILD_DIR)/src/codeGCN.o              \
    $(BUILD_DIR)/src/soundGCN.o             \
    $(BUILD_DIR)/asm/ce-j/frame.o           \
    $(BUILD_DIR)/src/system.o               \
    $(BUILD_DIR)/src/cpu.o                  \
    $(BUILD_DIR)/src/pif.o                  \
    $(BUILD_DIR)/src/ram.o                  \
    $(BUILD_DIR)/src/rom.o                  \
    $(BUILD_DIR)/src/rdp.o                  \
    $(BUILD_DIR)/src/rdb.o                  \
    $(BUILD_DIR)/src/rsp.o                  \
    $(BUILD_DIR)/src/mips.o                 \
    $(BUILD_DIR)/src/disk.o                 \
    $(BUILD_DIR)/src/flash.o                \
    $(BUILD_DIR)/src/sram.o                 \
    $(BUILD_DIR)/src/audio.o                \
    $(BUILD_DIR)/src/video.o                \
    $(BUILD_DIR)/src/serial.o               \
    $(BUILD_DIR)/src/library.o              \
    $(BUILD_DIR)/src/peripheral.o           \
    $(BUILD_DIR)/src/_frameGCNcc.o          \
    $(BUILD_DIR)/src/_buildtev.o            \
    $(BUILD_DIR)/asm/ce-j/PPCArch.o              \
    $(BUILD_DIR)/asm/ce-j/OS.o                   \
    $(BUILD_DIR)/asm/ce-j/OSAlarm.o              \
    $(BUILD_DIR)/asm/ce-j/OSAlloc.o              \
    $(BUILD_DIR)/asm/ce-j/OSArena.o              \
    $(BUILD_DIR)/asm/ce-j/OSAudioSystem.o        \
    $(BUILD_DIR)/asm/ce-j/OSCache.o              \
    $(BUILD_DIR)/asm/ce-j/OSContext.o            \
    $(BUILD_DIR)/asm/ce-j/OSError.o              \
    $(BUILD_DIR)/asm/ce-j/OSFont.o               \
    $(BUILD_DIR)/asm/ce-j/OSInterrupt.o          \
    $(BUILD_DIR)/asm/ce-j/OSLink.o               \
    $(BUILD_DIR)/asm/ce-j/OSMessage.o            \
    $(BUILD_DIR)/asm/ce-j/OSMemory.o             \
    $(BUILD_DIR)/asm/ce-j/OSMutex.o              \
    $(BUILD_DIR)/asm/ce-j/OSReboot.o             \
    $(BUILD_DIR)/asm/ce-j/OSReset.o              \
    $(BUILD_DIR)/asm/ce-j/OSResetSW.o            \
    $(BUILD_DIR)/asm/ce-j/OSRtc.o                \
    $(BUILD_DIR)/asm/ce-j/OSSync.o               \
    $(BUILD_DIR)/asm/ce-j/OSThread.o             \
    $(BUILD_DIR)/asm/ce-j/OSTime.o               \
    $(BUILD_DIR)/asm/ce-j/__start.o              \
    $(BUILD_DIR)/asm/ce-j/__ppc_eabi_init.o      \
    $(BUILD_DIR)/asm/ce-j/EXIBios.o              \
    $(BUILD_DIR)/asm/ce-j/EXIUart.o              \
    $(BUILD_DIR)/asm/ce-j/SIBios.o               \
    $(BUILD_DIR)/asm/ce-j/SISamplingRate.o       \
    $(BUILD_DIR)/asm/ce-j/vi.o                   \
    $(BUILD_DIR)/asm/ce-j/db.o                   \
    $(BUILD_DIR)/asm/ce-j/mtx.o                  \
    $(BUILD_DIR)/asm/ce-j/mtxvec.o               \
    $(BUILD_DIR)/asm/ce-j/mtx44.o                \
    $(BUILD_DIR)/asm/ce-j/GXInit.o               \
    $(BUILD_DIR)/asm/ce-j/GXFifo.o               \
    $(BUILD_DIR)/asm/ce-j/GXAttr.o               \
    $(BUILD_DIR)/asm/ce-j/GXMisc.o               \
    $(BUILD_DIR)/asm/ce-j/GXGeometry.o           \
    $(BUILD_DIR)/asm/ce-j/GXFrameBuf.o           \
    $(BUILD_DIR)/asm/ce-j/GXLight.o              \
    $(BUILD_DIR)/asm/ce-j/GXTexture.o            \
    $(BUILD_DIR)/asm/ce-j/GXBump.o               \
    $(BUILD_DIR)/asm/ce-j/GXTev.o                \
    $(BUILD_DIR)/asm/ce-j/GXPixel.o              \
    $(BUILD_DIR)/asm/ce-j/GXTransform.o          \
    $(BUILD_DIR)/asm/ce-j/GXPerf.o               \
    $(BUILD_DIR)/asm/ce-j/Padclamp.o             \
    $(BUILD_DIR)/asm/ce-j/Pad.o                  \
    $(BUILD_DIR)/asm/ce-j/dvdlow.o               \
    $(BUILD_DIR)/asm/ce-j/dvdfs.o                \
    $(BUILD_DIR)/asm/ce-j/dvd.o                  \
    $(BUILD_DIR)/asm/ce-j/dvdqueue.o             \
    $(BUILD_DIR)/asm/ce-j/dvderror.o             \
    $(BUILD_DIR)/asm/ce-j/dvdidutils.o           \
    $(BUILD_DIR)/asm/ce-j/dvdFatal.o             \
    $(BUILD_DIR)/asm/ce-j/fstload.o              \
    $(BUILD_DIR)/asm/ce-j/DEMOInit.o             \
    $(BUILD_DIR)/asm/ce-j/DEMOPuts.o             \
    $(BUILD_DIR)/asm/ce-j/DEMOFont.o             \
    $(BUILD_DIR)/asm/ce-j/DEMOPad.o              \
    $(BUILD_DIR)/asm/ce-j/DEMOStats.o            \
    $(BUILD_DIR)/asm/ce-j/ai.o                   \
    $(BUILD_DIR)/asm/ce-j/ar.o                   \
    $(BUILD_DIR)/asm/ce-j/dsp.o                  \
    $(BUILD_DIR)/asm/ce-j/dsp_debug.o            \
    $(BUILD_DIR)/asm/ce-j/dsp_task.o             \
    $(BUILD_DIR)/asm/ce-j/CARDBios.o             \
    $(BUILD_DIR)/asm/ce-j/CARDUnlock.o           \
    $(BUILD_DIR)/asm/ce-j/CARDRdwr.o             \
    $(BUILD_DIR)/asm/ce-j/CARDBlock.o            \
    $(BUILD_DIR)/asm/ce-j/CARDDir.o              \
    $(BUILD_DIR)/asm/ce-j/CARDCheck.o            \
    $(BUILD_DIR)/asm/ce-j/CARDMount.o            \
    $(BUILD_DIR)/asm/ce-j/CARDFormat.o           \
    $(BUILD_DIR)/asm/ce-j/CARDOpen.o             \
    $(BUILD_DIR)/asm/ce-j/CARDCreate.o           \
    $(BUILD_DIR)/asm/ce-j/CARDRead.o             \
    $(BUILD_DIR)/asm/ce-j/CARDWrite.o            \
    $(BUILD_DIR)/asm/ce-j/CARDDelete.o           \
    $(BUILD_DIR)/asm/ce-j/CARDStat.o             \
    $(BUILD_DIR)/asm/ce-j/CARDNet.o              \
    $(BUILD_DIR)/asm/ce-j/THPDec.o               \
    $(BUILD_DIR)/asm/ce-j/THPAudio.o             \
    $(BUILD_DIR)/asm/ce-j/texPalette.o           \
    $(BUILD_DIR)/asm/ce-j/mainloop.o             \
    $(BUILD_DIR)/asm/ce-j/nubevent.o             \
    $(BUILD_DIR)/asm/ce-j/nubinit.o              \
    $(BUILD_DIR)/asm/ce-j/msg.o                  \
    $(BUILD_DIR)/asm/ce-j/msgbuf.o               \
    $(BUILD_DIR)/asm/ce-j/serpoll.o              \
    $(BUILD_DIR)/asm/ce-j/usr_put.o              \
    $(BUILD_DIR)/asm/ce-j/dispatch.o             \
    $(BUILD_DIR)/asm/ce-j/msghndlr.o             \
    $(BUILD_DIR)/asm/ce-j/support.o              \
    $(BUILD_DIR)/asm/ce-j/mutex_TRK.o            \
    $(BUILD_DIR)/asm/ce-j/notify.o               \
    $(BUILD_DIR)/asm/ce-j/flush_cache.o          \
    $(BUILD_DIR)/asm/ce-j/mem_TRK.o              \
    $(BUILD_DIR)/asm/ce-j/__exception.o          \
    $(BUILD_DIR)/asm/ce-j/targimpl.o             \
    $(BUILD_DIR)/asm/ce-j/dolphin_trk.o          \
    $(BUILD_DIR)/asm/ce-j/mpc_7xx_603e.o         \
    $(BUILD_DIR)/asm/ce-j/main_TRK.o             \
    $(BUILD_DIR)/asm/ce-j/dolphin_trk_glue.o     \
    $(BUILD_DIR)/asm/ce-j/targcont.o             \
    $(BUILD_DIR)/asm/ce-j/__mem.o                \
    $(BUILD_DIR)/asm/ce-j/__va_arg.o             \
    $(BUILD_DIR)/asm/ce-j/global_destructor_chain.o \
    $(BUILD_DIR)/asm/ce-j/runtime.o              \
    $(BUILD_DIR)/asm/ce-j/abort_exit.o           \
    $(BUILD_DIR)/asm/ce-j/ansi_files.o           \
    $(BUILD_DIR)/asm/ce-j/ansi_fp.o              \
    $(BUILD_DIR)/asm/ce-j/buffer_io.o            \
    $(BUILD_DIR)/asm/ce-j/critical_regions.ppc_eabi.o \
    $(BUILD_DIR)/asm/ce-j/ctype.o                \
    $(BUILD_DIR)/asm/ce-j/direct_io.o            \
    $(BUILD_DIR)/asm/ce-j/errno.o                \
    $(BUILD_DIR)/asm/ce-j/mbstring.o             \
    $(BUILD_DIR)/asm/ce-j/mem.o                  \
    $(BUILD_DIR)/asm/ce-j/mem_funcs.o            \
    $(BUILD_DIR)/asm/ce-j/misc_io.o              \
    $(BUILD_DIR)/asm/ce-j/printf.o               \
    $(BUILD_DIR)/asm/ce-j/scanf.o                \
    $(BUILD_DIR)/asm/ce-j/string.o               \
    $(BUILD_DIR)/asm/ce-j/strtoul.o              \
    $(BUILD_DIR)/asm/ce-j/uart_console_io.o      \
    $(BUILD_DIR)/asm/ce-j/float.o                \
    $(BUILD_DIR)/asm/ce-j/wchar_io.o             \
    $(BUILD_DIR)/asm/ce-j/e_asin.o               \
    $(BUILD_DIR)/asm/ce-j/e_pow.o                \
    $(BUILD_DIR)/asm/ce-j/fminmaxdim.o           \
    $(BUILD_DIR)/asm/ce-j/s_ceil.o               \
    $(BUILD_DIR)/asm/ce-j/s_copysign.o           \
    $(BUILD_DIR)/asm/ce-j/s_floor.o              \
    $(BUILD_DIR)/asm/ce-j/s_frexp.o              \
    $(BUILD_DIR)/asm/ce-j/s_ldexp.o              \
    $(BUILD_DIR)/asm/ce-j/w_pow.o                \
    $(BUILD_DIR)/asm/ce-j/hyperbolicsf.o         \
    $(BUILD_DIR)/asm/ce-j/log10f.o               \
    $(BUILD_DIR)/asm/ce-j/trigf.o                \
    $(BUILD_DIR)/asm/ce-j/math_inlines.o         \
    $(BUILD_DIR)/asm/ce-j/common_float_tables.o  \
    $(BUILD_DIR)/asm/ce-j/AmcExi2Stubs.o         \
    $(BUILD_DIR)/asm/ce-j/DebuggerDriver.o       \
    $(BUILD_DIR)/asm/ce-j/odenotstub.o           \
