# See config.example.yml for documentation.
name: oot-gc
object: orig/mq-j/main.dol
hash: 7bfa2acdf675b5c5442890688d1e0293817ad63f
symbols: config/mq-j/symbols.txt
splits: config/mq-j/splits.txt
mw_comment_version: 8

extract:
# xlCoreGCN.c
- symbol: gTgPcTPL
  header: gTgPcTPL.inc
# simGCN.c
- symbol: gcoverOpen
  header: gcoverOpen.inc
- symbol: gnoDisk
  header: gnoDisk.inc
- symbol: gretryErr
  header: gretryErr.inc
- symbol: gfatalErr
  header: gfatalErr.inc
- symbol: gwrongDisk
  header: gwrongDisk.inc
- symbol: greadingDisk
  header: greadingDisk.inc
- symbol: gbar
  header: gbar.inc
- symbol: gyes
  header: gyes.inc
- symbol: gno
  header: gno.inc
- symbol: gmesgOK
  header: gmesgOK.inc
