# See config.example.yml for documentation.
name: oot-gc
object: orig/ce-e/main.dol
hash: 8c5c365ae2df34c4cb27e86eb1cf30f2a2e4cd1b
symbols: config/ce-e/symbols.txt
splits: config/ce-e/splits.txt
mw_comment_version: 8

extract:
# xlCoreGCN.c
- symbol: gTgPcTPL
  header: gTgPcTPL.inc
# simGCN.c
- symbol: gcoverOpen
  header: gcoverOpen.inc
- symbol: gnoDisk
  header: gnoDisk.inc
- symbol: gretryErr
  header: gretryErr.inc
- symbol: gfatalErr
  header: gfatalErr.inc
- symbol: gwrongDisk
  header: gwrongDisk.inc
- symbol: greadingDisk
  header: greadingDisk.inc
- symbol: gyes
  header: gyes.inc
- symbol: gno
  header: gno.inc
- symbol: gmesgOK
  header: gmesgOK.inc
- symbol: gfrench_coverOpen
  header: gfrench_coverOpen.inc
- symbol: gfrench_noDisk
  header: gfrench_noDisk.inc
- symbol: gfrench_retryErr
  header: gfrench_retryErr.inc
- symbol: gfrench_fatalErr
  header: gfrench_fatalErr.inc
- symbol: gfrench_wrongDisk
  header: gfrench_wrongDisk.inc
- symbol: gfrench_readingDisk
  header: gfrench_readingDisk.inc
- symbol: gfrench_yes
  header: gfrench_yes.inc
- symbol: gfrench_no
  header: gfrench_no.inc
- symbol: gfrench_mesgOK
  header: gfrench_mesgOK.inc
- symbol: ggerman_coverOpen
  header: ggerman_coverOpen.inc
- symbol: ggerman_noDisk
  header: ggerman_noDisk.inc
- symbol: ggerman_retryErr
  header: ggerman_retryErr.inc
- symbol: ggerman_fatalErr
  header: ggerman_fatalErr.inc
- symbol: ggerman_wrongDisk
  header: ggerman_wrongDisk.inc
- symbol: ggerman_readingDisk
  header: ggerman_readingDisk.inc
- symbol: ggerman_yes
  header: ggerman_yes.inc
- symbol: ggerman_no
  header: ggerman_no.inc
- symbol: ggerman_mesgOK
  header: ggerman_mesgOK.inc
- symbol: gspanish_coverOpen
  header: gspanish_coverOpen.inc
- symbol: gspanish_noDisk
  header: gspanish_noDisk.inc
- symbol: gspanish_retryErr
  header: gspanish_retryErr.inc
- symbol: gspanish_fatalErr
  header: gspanish_fatalErr.inc
- symbol: gspanish_wrongDisk
  header: gspanish_wrongDisk.inc
- symbol: gspanish_readingDisk
  header: gspanish_readingDisk.inc
- symbol: gspanish_yes
  header: gspanish_yes.inc
- symbol: gspanish_no
  header: gspanish_no.inc
- symbol: gspanish_mesgOK
  header: gspanish_mesgOK.inc
- symbol: gitalian_coverOpen
  header: gitalian_coverOpen.inc
- symbol: gitalian_noDisk
  header: gitalian_noDisk.inc
- symbol: gitalian_retryErr
  header: gitalian_retryErr.inc
- symbol: gitalian_fatalErr
  header: gitalian_fatalErr.inc
- symbol: gitalian_wrongDisk
  header: gitalian_wrongDisk.inc
- symbol: gitalian_readingDisk
  header: gitalian_readingDisk.inc
- symbol: gitalian_yes
  header: gitalian_yes.inc
- symbol: gitalian_no
  header: gitalian_no.inc
- symbol: gitalian_mesgOK
  header: gitalian_mesgOK.inc
- symbol: gbar
  header: gbar.inc
